### PR TITLE
Prettier format the repository

### PR DESCRIPTION
**Pull request by ccope**
Purely formatting, plus adding a .git-blame-ignore-revs file to allow devs to hide the commit in git blame.

### CODE REVIEW

**Review by hallettj — DISMISSED** [review]
Looks great! One change I would make is to add a configuration file, `.prettierrc.json`, with an empty object, `{}`. It looks like you have used prettier's default settings, which I think is good. If there is no configuration file there is ambiguity over whether prettier should use its default settings, the custom prettier settings a user has configured in their IDE, or settings from some prettier config file in a parent or ancestor directory. A config file with an empty object makes explicit that default settings should be used.

It could be helpful to have an npm script for formatting in the `gnome-42` branch since I see you have a `package.json` file there.

I appreciate the work you have been doing on this project so much! I've come to depend on PaperWM.

**Comment by Thesola10** [comment]
Approved over at the discussion for #25

**Review by smichel17 — APPROVED** [review]
@ccope Can you:

- Bring this up to date again
- Add a `.prettierrc.json` file as @hallettj suggested
- Merge this
- Merge #25 into `master`

I have updated the branch protection rules (no approval required before merging PRs) so you can do this without waiting. Thanks!

**Comment by smichel17** [comment]
Just as a heads-up, we will need to bring this up to date at least one more time, post-merge, for the PR to get it merged back upstream. Hopefully that will be the last time though.

**Comment by smichel17** [comment]
See https://github.com/PaperWM-community/PaperWM/pull/25#issuecomment-1241279531

**Pull request closed without merging**
