### PR TITLE
Gestures obey natural-scroll touchpad setting (#373)

### PR DESCRIPTION
**Pull request by wraithm**
Hey, I wrote this PR (https://github.com/paperwm/PaperWM/pull/373) that got merged into the `develop` branch on the main repo. I upgraded to GNOME 40 and started using this repo. Great job! Things are mostly working fine. I noticed that my patch didn't make it onto the `next-release` branch. I figured I'd just re-open this PR with the same commit here. I tested this on my machine, and it works perfectly on GNOME 40. Same behavior as on the old setup.

Here's the commit message:

Closes #371

Right now when I three-finger scroll in Wayland, moving my hand to the
right makes the windows move to the right as if dragging the proverbial
paper. As in, scrolling moves the content, not the view. In Gnome's
mouse/trackpad settings, this is referred to as "Natural Scrolling". One
can disable "Natural Scrolling" such that two-finger scrolling results
in moving the view, not the content.

This commit makes PaperWM respect the natural-scroll touchpad global
setting. If unnatural scrolling is enabled in Gnome's global settings,
then PaperWM will use unnatural scroll touchpad gestures, and vice versa.

The scroll direction is encoded as either a 1 or -1 and checks the Gnome
settings every Clutter.TouchpadGesturePhase.BEGIN.

There could be an extension added to this to make this setting
toggle-able separately from Gnome's global settings. There could be a
separate setting that overrides the Gnome global setting. There could be
people who prefer unnatural scrolling for their browser and such but
natural scrolling for PaperWM.

### CODE REVIEW

**Comment by wraithm** [comment]
@michaelhthomas, what do you think about this?

**Comment by michaelhthomas** [comment]
Looks good to me! I'll give it a quick test, shouldn't be too much or a problem to merge since it was already merged upstream.

**Comment by smichel17** [comment]
Alternatively, we could merge all of upstream's `develop` branch into `next-release`. That might make the eventual merge back into upstream easier.

…it would really be nice to have just a few minutes to talk to @hedning about how he'd like to handle the situation instead of guessing at what will make things easier, though :/

**Comment by smichel17** [comment]
> Alternatively, we could merge all of upstream's develop branch into next-release. 

I did this in #29, so this is merged in now.

**Pull request closed without merging**
